openapi: 3.0.3
info:
  title: Bill pay application for XYZ corporation
  description: |-
    This is API design of bill pay application for XYZ corporation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

paths:
  /wallet/register:
    post:
      tags:
        - Wallet Service external
      summary: Resgister new customer
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        400:
          $ref: "#/components/responses/400"
        429:
          $ref: "#/components/responses/429"
        500:
          $ref: "#/components/responses/500"
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                type: "string"
                example : "Customer registerd"
  /wallet/addmoney/{emailId}:
    post:
      tags:
        - Wallet Service external
      summary: Resgister new customer
      parameters: 
        - in: path
          name: emailId
          schema:
            type: string
          required: true 
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Currency'
        required: true
      responses:
        400:
          $ref: "#/components/responses/400"
        429:
          $ref: "#/components/responses/429"
        500:
          $ref: "#/components/responses/500"
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                type: "string"
                example : "Customer registerd"
  
  /wallet/balance/{emailId}:
    get:
      tags: 
        - Wallet Service external
      summary: Get balance
      parameters: 
        - in: path
          name: emailId
          schema:
            type: string
          required: true  
      responses:
        400:
          $ref: "#/components/responses/400"
        429:
          $ref: "#/components/responses/429"
        500:
          $ref: "#/components/responses/500"
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Currency"
                
  /wallet/pay/{emailId}:            
    post:
      tags:
        - Wallet Service internal
      summary: Pay from wallet
      parameters: 
        - in: path
          name: emailId
          schema:
            type: string
          required: true  
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Currency'
        required: true
      responses:
        400:
          $ref: "#/components/responses/400"
        429:
          $ref: "#/components/responses/429"
        500:
          $ref: "#/components/responses/500"
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                type: "string"
                example : "Customer registerd"
                
  /billpay/pay/{emailId} :    
    post:
      tags:
        - Bill pay Service external
      summary: Pay from wallet
      parameters: 
        - in: path
          name: emailId
          schema:
            type: string
          required: true  
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        400:
          $ref: "#/components/responses/400"
        429:
          $ref: "#/components/responses/429"
        500:
          $ref: "#/components/responses/500"
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                type: "string"
                example : "Customer registerd"
  
  /billpay/fetchbillers:     
    get:
      tags: 
        - Bill pay Service external
      summary: Fetch billers
      responses:
        400:
          $ref: "#/components/responses/400"
        429:
          $ref: "#/components/responses/429"
        500:
          $ref: "#/components/responses/500"
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/fetchBillerResponse"
  
  /billpay/fetchhistory/{emailId}:     
    get:
      tags: 
        - Bill pay Service external
      summary: Fetch billers
      parameters: 
        - in: path
          name: emailId
          schema:
            type: string
          required: true  
      responses:
        400:
          $ref: "#/components/responses/400"
        429:
          $ref: "#/components/responses/429"
        500:
          $ref: "#/components/responses/500"
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/billingHistoryReponse"        
                
  /billpay/bulkpay/{emailId}:     
    post:
      tags: 
        - Bill pay Service external
      summary: Fetch billers
      parameters: 
        - in: path
          name: emailId
          schema:
            type: string
          required: true
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        400:
          $ref: "#/components/responses/400"
        429:
          $ref: "#/components/responses/429"
        500:
          $ref: "#/components/responses/500"
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                type: "string"
                example : "Customer registerd"    
    
    
    
    
components:
  responses:
    429:
      description: "Too Many Requests"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIFailure"
    404:
      description: "Resource Not Found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIFailure"
    400:
      description: "Bad Request"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIFailure"
    500:
      description: "Internal Server Error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIFailure"
    
      
            
  schemas:
    APIFailure:
      required:
        - "error"
      type: "object"
      properties:
        error:
          required:
            - "code"
            - "message"
          type: "object"
          properties:
            message:
              type: "string"
              description: "The message Info"
            code:
              type: "string"
              description: "The code error"
    
    fetchBillerResponse:
      type: object
      properties:
        billers :
          items: 
            $ref: "#/components/schemas/Biller" 
            
    billingHistoryReponse:        
      type: object
      properties:
        billers :
          items: 
            $ref: "#/components/schemas/BillingHistory" 
          
      
    
    Customer:
      type: object
      properties:
        emailId:
          type: string
          example: abc@gmail.com
          
  
    Currency:      
      type: object
      properties:
        amount:
          type: number
          example: 2
        currency:
          type: string
          example: "$"
          
    Biller:      
      type: object
      properties:
        id:
          type: string
          example: "vimobile123"
        name:
          type: string
          example: "VIMobile"      
    
    BillingHistory:
      type: object
      properties:
        billerName: 
          type: string
          example: "VIMobile"
        billingDate:
          type: string
          example: "01 Nov 2022"
        amount: 
          type: number
          example: 800
    
    
